# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3fe04c9b21a84d2b18b19740df768affa67c29f34c42a74686267317b553889fc6fa777538935d94180bd0e21ae5e3fd72ab1ce62c055b436cc4641b577b875

test:
  secret_key_base: 4cd6ab0430f108c026f90757c143e03c32c0687400bb414b5c756cdbda0ad7186f3ddd166fd960d62359c3e55b564d337ac2b232c0d89c64801b694f87526e5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
